// <auto-generated />
namespace Capstone.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PartnershipNightChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PartnershipNightChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201405252312578_PartnershipNightChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
